### ISSUE TITLE
Emmet not working in Dreamweaver CC 2015

### ISSUE THREAD

**Issue by RuthAdele** [emmetio/dreamweaver#12]
Have installed extension (and Adobe Extension Manager CC 2015 says it is installed), but there is no mention of Emmet in Commands or Keyboard Shortcuts within Dreamweaver. 
have tried closing the program, and restarted my computer.

Is there a step missing in this latest version of Dreamweaver that I need to do in order to get the extension working again? Or perhaps it is incompatible the latest version? (I hope not!)

Sometimes I hate upgrading stuff...

**Comment by RuthAdele** [comment]
Also, Adobe have released a statement saying that extensions will no longer be supported (https://www.adobeexchange.com/resources/27). 
Do you plan on making Emmet an Adobe Add-on for future use?

**Comment by sergeche** [comment]
Dreamweaver CC now has built-in Emmet support

**Comment by RuthAdele** [comment]
Oh? Do you know how to enable it?
I upgraded to CC 2015 the other day and lost Emmet in the process, and I'm so lost without it! (it's the best tool ever)

**Comment by sergeche** [comment]
I don’t know, try to check this out: https://www.adobe.com/ru/products/dreamweaver/features.html

**Comment by RuthAdele** [comment]
Thanks for that! Putting this here in case someone else comes across the same issues as me:

So by default the expand selection is there, with the keyboard shortcut 'Tab'. Unfortunately you currently can't assign it to your own keyboard shortcut, but I found a forum post that mentions they might be working on that, and it might change in the future. (https://forums.adobe.com/thread/1874760)

At least I can still use it, I just have to re-learn my shortcuts :)

Thanks for everything! 
Ruth.
